"""Typed Pydantic models for FortiSOAR records and API result shapes.

``BaseRecord`` is the dict-compatible base for entity records; concrete models
live in :mod:`pyfsr.models._generated`.  ``ApiResult`` is the lighter base for
typed integration API response shapes (connector configs, job statuses, etc.)
defined in :mod:`pyfsr.models._integration`.

``MODEL_REGISTRY`` maps a module (collection) name to its model so
:class:`~pyfsr.records.RecordSet` can parse responses into the right type,
falling back to ``BaseRecord`` for modules without a curated model.
"""

from __future__ import annotations

from ._agents import Agent, AgentConnectorStatus
from ._ai import (
    AgentConfig,
    AgentConfigDTO,
    AgentRecord,
    AgentRunResult,
    ConnectorMcpCandidates,
    InvestigationHandle,
    InvestigationQuestion,
    InvestigationResult,
    LLMConfig,
    LLMProvider,
    MCPServerConfig,
    MCPServerRef,
    MCPServerStatus,
    MCPTool,
    MCPToolResult,
    MCPValidateResult,
    ToolCall,
)
from ._ai_agent_package import (
    AgentInfo,
    AgentMemory,
    AgentPackage,
    AgentPrompt,
    AgentPromptFile,
)
from ._app_config import NavItem, NavRequire, NavState
from ._audit import AuditActivity, ExecutionContext, LifecycleEntry, RecordLifecycle
from ._export import (
    ConnectorSelection,
    ModuleSelection,
    PlaybookCollectionSelection,
    RecordSet,
    ViewTemplateSelection,
)
from ._generated import Alert, Comment, Incident, Task
from ._integration import (
    ApiResult,
    ConfigValidationError,
    ConfigValidationResult,
    ConnectorConfig,
    ConnectorConfigSummary,
    ConnectorDefinition,
    DependencyStatus,
    EnsureVersionResult,
    ExecuteResult,
    ExportJobResult,
    HealthcheckResult,
    ImportJobResult,
    IngestionMetadata,
    IngestionPlaybooks,
    IngestionSetupResult,
    IngestionStatus,
    IngestionTeardownResult,
    InstalledConnector,
    InstallJobStatus,
    IntegrationListEnvelope,
    LogMessage,
    Operation,
    OperationParam,
    ParamOption,
)
from ._modules_admin import (
    AttributeBulkAction,
    AttributeMetadata,
    AttributeValidation,
    DefaultSortEntry,
    InvalidDraft,
    ModuleDescriptions,
    ModuleMetadata,
    PendingChange,
    PublishedModelMetadata,
    StagingModelMetadata,
)
from ._playbooks import (
    ApprovalRequest,
    CreatePlaybookRequest,
    CreateVersionRequest,
    PlaybookVersion,
    ResumeRequest,
    RunEnv,
    RunFailure,
    RunNode,
    RunResult,
    RunStep,
    RunStepSnapshot,
    RunSummary,
    TriggerActionRequest,
    TriggerRequest,
    TriggerResponse,
    VersionDiff,
    VersionStepDelta,
    WaitProgress,
)
from ._rules import DeliveryRule, PreprocessingRule, RuleChannel
from ._schedules import CrontabScheduleModel, ScheduledTask
from ._stix import (
    StixAttackPattern,
    StixBundle,
    StixCampaign,
    StixIndicator,
    StixIntrusionSet,
    StixMalware,
    StixObject,
    StixReport,
    StixThreatActor,
    StixTool,
    StixVulnerability,
    parse_stix_object,
)
from ._system import (
    Actor,
    AggregateRow,
    AIAgent,
    ApiKey,
    ApiKeyMaterial,
    ApiKeyUser,
    Appliance,
    Attachment,
    ConnectorOperation,
    ConnectorVersionInfo,
    ContentHubConnector,
    ContentHubItem,
    DailyActionCount,
    EmailTemplate,
    ExportConnectorRef,
    ExportOptions,
    ExportTemplate,
    FeaturedTag,
    FileRecord,
    ImportJob,
    ManualInput,
    ManualInputForm,
    ManualInputOption,
    ManualInputResume,
    ManualInputSchema,
    ManualInputVariable,
    ModulePermission,
    NavigationView,
    Notification,
    NotificationPurge,
    PicklistItem,
    PicklistName,
    PostInstallConfig,
    PostInstallWidget,
    QueryDefinition,
    QueryFilter,
    RepoConnectorEntry,
    Report,
    ResponseMapping,
    ReusableBlock,
    Role,
    SolutionPack,
    SolutionPackInfo,
    SolutionPackInstallResponse,
    SystemQuery,
    SystemViewTemplate,
    Team,
    User,
    Widget,
    WidgetInfo,
    Workflow,
    WorkflowCollection,
    WorkflowRun,
)
from ._taxii import (
    StixBundleResult,
    TaxiiCollection,
    TaxiiDiscovery,
    TaxiiManifest,
    TaxiiManifestEntry,
    TaxiiObjectsEnvelope,
)
from ._widgets import WidgetRecord
from .base import BaseRecord
from .types import PicklistIRI, RecordIRI

# Module (collection) name → model. Keys are the FortiSOAR plural module slugs
# used in ``/api/3/<module>`` paths. The workflow entries are stable,
# platform-owned schemas (see ``_system`` and the SDK roadmap §7).
MODEL_REGISTRY: dict[str, type[BaseRecord]] = {
    "alerts": Alert,
    "incidents": Incident,
    "tasks": Task,
    "comments": Comment,
    "workflows": Workflow,
    "workflow_collections": WorkflowCollection,
    "files": FileRecord,
    "people": User,
    "teams": Team,
    "email_templates": EmailTemplate,
    "roles": Role,
    "api_keys": ApiKey,
    "system_queries": SystemQuery,
}


def model_for(module: str) -> type[BaseRecord]:
    """Return the registered model for ``module``, or ``BaseRecord`` if none."""
    return MODEL_REGISTRY.get(module, BaseRecord)


# `_integration` annotates ingestion payloads as `Workflow` but cannot import it at
# module scope (`_system` imports ApiResult from `_integration`). Both modules are
# loaded by now, so resolve the deferred reference.
from ._system import Workflow as _Workflow  # noqa: E402

for _model in (IngestionPlaybooks, IngestionSetupResult, IngestionStatus):
    _model.model_rebuild(_types_namespace={"Workflow": _Workflow})

__all__ = [
    "IngestionSetupResult",
    "IngestionStatus",
    "IngestionTeardownResult",
    "IngestionPlaybooks",
    "IngestionMetadata",
    "DependencyStatus",
    # base classes
    "BaseRecord",
    "ApiResult",
    # IRI NewTypes
    "PicklistIRI",
    "RecordIRI",
    # config-export option entries
    "ModuleSelection",
    "RecordSet",
    "ConnectorSelection",
    "PlaybookCollectionSelection",
    "ViewTemplateSelection",
    # agent records
    "Agent",
    "AgentConnectorStatus",
    "AgentInfo",
    "AgentMemory",
    "AgentPackage",
    "AgentPrompt",
    "AgentPromptFile",
    # FortiAI agentic-service shapes (client.ai)
    "AgentConfig",
    "AgentConfigDTO",
    "AgentRecord",
    "ConnectorMcpCandidates",
    "AgentRunResult",
    "InvestigationHandle",
    "InvestigationQuestion",
    "InvestigationResult",
    "LLMConfig",
    "LLMProvider",
    "MCPServerConfig",
    "MCPServerRef",
    "MCPServerStatus",
    "MCPTool",
    "MCPToolResult",
    "MCPValidateResult",
    "ToolCall",
    # integration API result shapes
    "InstalledConnector",
    "ConnectorConfigSummary",
    "ConnectorConfig",
    "ConnectorDefinition",
    "Operation",
    "OperationParam",
    "ParamOption",
    "ConfigValidationResult",
    "ConfigValidationError",
    "HealthcheckResult",
    "ExecuteResult",
    "IntegrationListEnvelope",
    "InstallJobStatus",
    "EnsureVersionResult",
    "ImportJobResult",
    "ExportJobResult",
    "LogMessage",
    # entity records
    "Actor",
    "Appliance",
    "Alert",
    "Incident",
    "Task",
    "Comment",
    "Workflow",
    "WorkflowCollection",
    "ReusableBlock",
    "WorkflowRun",
    # playbook-run output shapes
    "RunSummary",
    "RunStep",
    "RunStepSnapshot",
    "RunEnv",
    "RunNode",
    "RunFailure",
    "RunResult",
    "WaitProgress",
    "TriggerResponse",
    # playbook version-control shapes (workflow_versions snapshots)
    "PlaybookVersion",
    "VersionDiff",
    "VersionStepDelta",
    # playbook write-request bodies
    "TriggerRequest",
    "TriggerActionRequest",
    "ResumeRequest",
    "ApprovalRequest",
    "CreatePlaybookRequest",
    "CreateVersionRequest",
    "FileRecord",
    "Attachment",
    "ExportTemplate",
    "ExportOptions",
    "ExportConnectorRef",
    "User",
    "Team",
    "EmailTemplate",
    "Notification",
    "NotificationPurge",
    "ManualInput",
    "ManualInputForm",
    "ManualInputOption",
    "ManualInputResume",
    "ManualInputSchema",
    "ManualInputVariable",
    "ResponseMapping",
    "Role",
    "ModulePermission",
    "ApiKey",
    "ApiKeyMaterial",
    "ApiKeyUser",
    "ContentHubItem",
    "DailyActionCount",
    "FeaturedTag",
    "SolutionPack",
    "SolutionPackInstallResponse",
    "PostInstallConfig",
    "PostInstallWidget",
    "SystemQuery",
    "QueryFilter",
    "QueryDefinition",
    "SolutionPackInfo",
    "AIAgent",
    "Report",
    "NavigationView",
    "DeliveryRule",
    "RuleChannel",
    "PreprocessingRule",
    "SystemViewTemplate",
    "ImportJob",
    "ContentHubConnector",
    "Widget",
    "WidgetInfo",
    "WidgetRecord",
    "RepoConnectorEntry",
    "ConnectorOperation",
    "ConnectorVersionInfo",
    "PicklistItem",
    "PicklistName",
    "AggregateRow",
    "MODEL_REGISTRY",
    "model_for",
    # module admin
    "AttributeValidation",
    "AttributeBulkAction",
    "AttributeMetadata",
    "DefaultSortEntry",
    "ModuleDescriptions",
    "ModuleMetadata",
    "StagingModelMetadata",
    "PublishedModelMetadata",
    "PendingChange",
    "InvalidDraft",
    # application navigation
    "NavItem",
    "NavRequire",
    "NavState",
    # scheduled (periodic) tasks
    "ScheduledTask",
    "CrontabScheduleModel",
    # audit / lifecycle
    "AuditActivity",
    "LifecycleEntry",
    "RecordLifecycle",
    "ExecutionContext",
    # STIX 2.1 objects
    "StixObject",
    "StixIndicator",
    "StixMalware",
    "StixThreatActor",
    "StixCampaign",
    "StixAttackPattern",
    "StixIntrusionSet",
    "StixTool",
    "StixVulnerability",
    "StixReport",
    "StixBundle",
    "parse_stix_object",
    # TAXII 2.1 responses + STIX bundle ingest
    "TaxiiDiscovery",
    "TaxiiCollection",
    "TaxiiManifestEntry",
    "TaxiiManifest",
    "TaxiiObjectsEnvelope",
    "StixBundleResult",
]
