[project]
name = "pyfsr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dylan Spille", email = "dspille@fortinet.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
pyfsr = "pyfsr:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
