"""Live probe of query operators against FortiSOAR appliance.

Tests each operator in OPERATOR_SPECS by POSTing to /api/query/alerts and
recording HTTP status, error messages, and result counts. Results are written to
tests/resources/operator_matrix.json for repeatability and CI validation.

Assertions check that leaf operators return 200 and trigger-only operators
return non-200 (they are invalid on /api/query/).

Run with: pytest -m integration tests/integration/test_operator_matrix_integration.py -s
Requires a live appliance (FSR_* env or examples/config.toml).
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

import pytest

from pyfsr.query_models import OPERATOR_SPECS

pytestmark = pytest.mark.integration

PROBE_MODULE = "alerts"
RESOURCE_DIR = Path(__file__).parent.parent / "resources"


def _build_query_body(operator: str, field: str, value) -> dict:
    """Build a minimal query body for testing an operator."""
    return {
        "logic": "AND",
        "filters": [
            {
                "field": field,
                "operator": operator,
                **({"value": value} if value is not None else {}),
            }
        ],
    }


def _probe_operator(client, operator: str, field: str, value) -> dict:
    """POST a query with the operator and return status + metadata."""
    spec = OPERATOR_SPECS[operator]
    body = _build_query_body(operator, field, value)

    try:
        resp = client.session.post(
            f"{client.base_url}/api/query/{PROBE_MODULE}",
            json=body,
        )
        result_count = 0
        error_msg = None

        if resp.status_code == 200:
            data = resp.json()
            result_count = len(data.get("hydra:member", []))
        else:
            try:
                error_msg = resp.json().get("message") or resp.text[:200]
            except Exception:
                error_msg = resp.text[:200]

        return {
            "operator": operator,
            "category": spec.category,
            "arity": spec.arity.value,
            "http_status": resp.status_code,
            "error_message": error_msg,
            "result_count": result_count if resp.status_code == 200 else None,
        }
    except Exception as e:
        return {
            "operator": operator,
            "category": spec.category,
            "arity": spec.arity.value,
            "http_status": None,
            "error_message": f"Exception: {type(e).__name__}: {str(e)[:200]}",
            "result_count": None,
        }


def test_operator_matrix_all_operators(client):
    """Probe all operators and write results to the fixture."""
    # Operator -> (field, value) mapping for the alerts module
    operator_map = {
        "eq": ("name", "__probe__"),
        "neq": ("name", "__probe__"),
        "lt": ("createDate", "2020-01-01T00:00:00.000Z"),
        "lte": ("createDate", "2020-01-01T00:00:00.000Z"),
        "gt": ("createDate", "2020-01-01T00:00:00.000Z"),
        "gte": ("createDate", "2020-01-01T00:00:00.000Z"),
        "in": ("name", ["__probe__"]),
        "nin": ("name", ["__probe__"]),
        "in_all": ("name", ["__probe__"]),
        "like": ("name", "%probe%"),
        "notlike": ("name", "%probe%"),
        "contains": ("description", "probe"),
        "exists": ("name", True),
        "isnull": ("name", True),
        "changed": ("name", None),
    }

    results = []
    for operator_name in sorted(OPERATOR_SPECS.keys()):
        if operator_name not in operator_map:
            # Skip operators with no mapping (shouldn't happen)
            continue

        field, value = operator_map[operator_name]
        result = _probe_operator(client, operator_name, field, value)
        results.append(result)
        print(f"\n  {operator_name:12} → {result['http_status']:3} {result['error_message'] or 'OK'}")

    # Build the fixture
    fixture = {
        "_note": (
            "Generated by tests/integration/test_operator_matrix_integration.py. "
            "Run with pytest -m integration to refresh."
        ),
        "appliance_version": getattr(client, "_appliance_version", None),
        "generated": datetime.utcnow().isoformat() + "Z",
        "results": results,
    }

    # Write to the fixture file
    RESOURCE_DIR.mkdir(parents=True, exist_ok=True)
    fixture_path = RESOURCE_DIR / "operator_matrix.json"
    with open(fixture_path, "w") as f:
        json.dump(fixture, f, indent=2)

    print(f"\n\n[wrote] {fixture_path}")

    # Assertions: leaf operators should work, trigger-only should not
    leaf_results = [r for r in results if r["category"] == "leaf"]
    trigger_results = [r for r in results if r["category"] == "trigger"]

    for result in leaf_results:
        assert result["http_status"] == 200, (
            f"leaf operator {result['operator']!r} should return 200, "
            f"got {result['http_status']}: {result['error_message']}"
        )

    for result in trigger_results:
        assert result["http_status"] != 200, (
            f"trigger operator {result['operator']!r} should NOT return 200 on /api/query/, got {result['http_status']}"
        )

    print(f"\n[asserts] {len(leaf_results)} leaf operators valid, {len(trigger_results)} trigger operators rejected")
