"""
PyFSR: Python client for the FortiSOAR REST API.

For detailed documentation, visit: https://ftnt-dspille.github.io/pyfsr/
"""

from .api.connectors import pack_connector
from .appliance import Appliance
from .client import FortiSOAR
from .config import EnvConfig
from .models import (
    MODEL_REGISTRY,
    Alert,
    ApiResult,
    BaseRecord,
    Comment,
    ConfigValidationResult,
    ConnectorConfig,
    ConnectorConfigSummary,
    ConnectorOperation,
    ConnectorVersionInfo,
    ContentHubConnector,
    ContentHubItem,
    EnsureVersionResult,
    ExecuteResult,
    ExportJobResult,
    FeaturedTag,
    HealthcheckResult,
    ImportJob,
    ImportJobResult,
    Incident,
    InstalledConnector,
    InstallJobStatus,
    ModulePermission,
    PicklistIRI,
    RecordIRI,
    RunEnv,
    RunFailure,
    RunStep,
    RunSummary,
    SolutionPack,
    SolutionPackInstallResponse,
    Task,
    TriggerResponse,
    Widget,
    Workflow,
    WorkflowCollection,
    WorkflowRun,
    model_for,
)
from .pagination import HydraPage, paginate
from .projection import SUMMARY_FIELDS, project, project_record, to_jsonable
from .query import Query
from .query_models import OPERATOR_SPECS, QueryBody
from .records import RecordSet
from .tools import (
    REGISTRY,
    ToolSpec,
    dispatch,
    get_tool,
    list_tools,
    to_anthropic_tools,
    to_openai_tools,
    tool_schemas,
)

try:
    # Generated by hatch-vcs at build time from the latest git tag.
    from ._version import __version__
except ImportError:  # pragma: no cover - source checkout without a build
    __version__ = "0.0.0+unknown"

__all__ = [
    "FortiSOAR",
    "Appliance",
    "EnvConfig",
    "pack_connector",
    "Query",
    "QueryBody",
    "OPERATOR_SPECS",
    "RecordSet",
    "HydraPage",
    "paginate",
    "BaseRecord",
    "PicklistIRI",
    "RecordIRI",
    "ApiResult",
    "InstalledConnector",
    "ConnectorConfigSummary",
    "ConnectorConfig",
    "ConfigValidationResult",
    "HealthcheckResult",
    "ExecuteResult",
    "InstallJobStatus",
    "EnsureVersionResult",
    "ImportJobResult",
    "ExportJobResult",
    "Alert",
    "Incident",
    "Task",
    "Comment",
    "Workflow",
    "WorkflowCollection",
    "WorkflowRun",
    "RunSummary",
    "RunStep",
    "RunEnv",
    "RunFailure",
    "TriggerResponse",
    "ContentHubItem",
    "FeaturedTag",
    "SolutionPack",
    "SolutionPackInstallResponse",
    "ImportJob",
    "ContentHubConnector",
    "Widget",
    "ConnectorOperation",
    "ConnectorVersionInfo",
    "ModulePermission",
    "MODEL_REGISTRY",
    "model_for",
    # projection
    "project",
    "project_record",
    "to_jsonable",
    "SUMMARY_FIELDS",
    # agent tool registry
    "ToolSpec",
    "REGISTRY",
    "list_tools",
    "get_tool",
    "dispatch",
    "tool_schemas",
    "to_anthropic_tools",
    "to_openai_tools",
    "__version__",
]
