"""
PyFSR: Python client for the FortiSOAR REST API.

For detailed documentation, visit: https://ftnt-dspille.github.io/pyfsr/
"""

from .client import FortiSOAR
from .pagination import HydraPage, paginate
from .query import Query
from .records import RecordSet

try:
    # Generated by hatch-vcs at build time from the latest git tag.
    from ._version import __version__
except ImportError:  # pragma: no cover - source checkout without a build
    __version__ = "0.0.0+unknown"

__all__ = [
    "FortiSOAR",
    "Query",
    "RecordSet",
    "HydraPage",
    "paginate",
    "__version__",
]
