"""Unit tests for operator matrix fixture validation.

Loads the operator_matrix.json fixture (generated by the integration probe) and
validates that it's consistent with OPERATOR_SPECS. These tests run offline (no
live appliance) and enforce the operator knowledge base.

If operator_matrix.json is in stub state (results=[]), all assertions are skipped
(expected before the integration probe runs).
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from pyfsr.query_models import OPERATOR_SPECS

FIXTURE_PATH = Path(__file__).parent.parent / "resources" / "operator_matrix.json"


@pytest.fixture
def operator_matrix():
    """Load the operator matrix fixture."""
    with open(FIXTURE_PATH) as f:
        return json.load(f)


class TestOperatorMatrixStub:
    """Tests that run even when the fixture is in stub state (results=[])."""

    def test_fixture_file_exists(self):
        """Operator matrix fixture file exists."""
        assert FIXTURE_PATH.exists(), f"fixture not found: {FIXTURE_PATH}"

    def test_fixture_structure(self, operator_matrix):
        """Fixture has the expected top-level structure."""
        assert "results" in operator_matrix
        assert "generated" in operator_matrix
        assert "_note" in operator_matrix
        assert isinstance(operator_matrix["results"], list)


class TestOperatorMatrixResults:
    """Tests that validate the results. Skipped if the fixture is empty."""

    def test_all_operators_in_matrix(self, operator_matrix):
        """Every operator in OPERATOR_SPECS appears in the matrix results."""
        if not operator_matrix["results"]:
            pytest.skip("operator_matrix fixture in stub state (no probe run yet)")

        matrix_ops = {r["operator"] for r in operator_matrix["results"]}
        spec_ops = set(OPERATOR_SPECS.keys())
        assert matrix_ops == spec_ops, (
            f"mismatch: spec has {spec_ops - matrix_ops}, matrix has extra {matrix_ops - spec_ops}"
        )

    def test_leaf_operators_return_200(self, operator_matrix):
        """Every leaf operator should return HTTP 200 on /api/query/."""
        if not operator_matrix["results"]:
            pytest.skip("operator_matrix fixture in stub state (no probe run yet)")

        leaf_ops = [r for r in operator_matrix["results"] if r["category"] == "leaf"]
        for result in leaf_ops:
            assert result["http_status"] == 200, (
                f"leaf operator {result['operator']!r} returned {result['http_status']}: {result['error_message']}"
            )

    def test_trigger_operators_not_on_api_query(self, operator_matrix):
        """Trigger-only operators should NOT return 200 on /api/query/."""
        if not operator_matrix["results"]:
            pytest.skip("operator_matrix fixture in stub state (no probe run yet)")

        trigger_ops = [r for r in operator_matrix["results"] if r["category"] == "trigger"]
        for result in trigger_ops:
            assert result["http_status"] != 200, (
                f"trigger operator {result['operator']!r} should not work on /api/query/, got {result['http_status']}"
            )

    def test_operator_arity_matches_spec(self, operator_matrix):
        """Every result's arity matches the OPERATOR_SPECS entry."""
        if not operator_matrix["results"]:
            pytest.skip("operator_matrix fixture in stub state (no probe run yet)")

        for result in operator_matrix["results"]:
            spec = OPERATOR_SPECS.get(result["operator"])
            assert spec is not None, f"unknown operator {result['operator']!r}"
            assert result["arity"] == spec.arity.value, (
                f"arity mismatch for {result['operator']}: spec {spec.arity.value!r} vs matrix {result['arity']!r}"
            )

    def test_operator_category_matches_spec(self, operator_matrix):
        """Every result's category matches the OPERATOR_SPECS entry."""
        if not operator_matrix["results"]:
            pytest.skip("operator_matrix fixture in stub state (no probe run yet)")

        for result in operator_matrix["results"]:
            spec = OPERATOR_SPECS.get(result["operator"])
            assert spec is not None, f"unknown operator {result['operator']!r}"
            assert result["category"] == spec.category, (
                f"category mismatch for {result['operator']}: spec {spec.category!r} vs matrix {result['category']!r}"
            )
