name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[docs]  # Install in editable mode
          pip list  # Debug: List installed packages

      - name: Debug Python path
        run: |
          python -c "import sys; print('\n'.join(sys.path))"
          python -c "import pyfsr; print(pyfsr.__file__)"

      - name: Build documentation
        run: |
          cd docs
          make clean  # Clean previous builds
          sphinx-build -b html source build/html -v  # Verbose output for debugging

      - name: Check documentation files
        run: |
          echo "Contents of docs/build/html:"
          ls -la docs/build/html/
          echo "\nContents of docs/build/html/api:"
          ls -la docs/build/html/api/ || echo "api directory not found"

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'  # Only deploy on main branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          force_orphan: true  # Clean up gh-pages branch
          full_commit_message: 'docs: update documentation'