name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install ".[docs]"

      - name: Debug PYTHONPATH
        run: |
          echo "Python path:"
          python -c "import sys; print('\n'.join(sys.path))"
          echo "Checking module import:"
          python -c "import pyfsr; print(pyfsr)"

      - name: Build documentation
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          sphinx-build -b html source build/html


      - name: Check documentation files
        run: |
          echo "Contents of docs/build/html:"
          ls -la docs/build/html/

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          force_orphan: true
          commit_message: 'docs: update documentation'
