name: Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/pyfsr/**'
      - 'tests/**'
      - 'pyproject.toml'
      - '.github/workflows/**'
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        description: 'The Git ref to checkout'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: '**/pyproject.toml'

      - name: Run tests
        run: |
          pytest tests/ --cov=pyfsr --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  docs:
    needs: test
    uses: ./.github/workflows/docs.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit