name: Publish Python Package

on:
  release:
    types: [ created ]

jobs:
  test:
    uses: ./.github/workflows/pr-tests.yml
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    needs: [ test ]
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: '**/pyproject.toml'

      - run: pip install build

      - run: python -m build

      - uses: pypa/gh-action-pypi-publish@release/v1